[tool.poetry]
name = "wuyubot"
version = "0.1.0"
description = "一个普通的nonebot实现"
authors = ["yeqiu6080 <yeqiu6080@outlook.com>"]
license = "AGPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
